# Generated by Django 6.0.7 on 2026-08-24 20:31

import django.db.models.deletion
import earth_observation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('boundary', models.JSONField(validators=[earth_observation.models.validate_polygon])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observation_areas', to='locations.county')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_observation_areas', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_areas', to='locations.ward')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('imagery_source', models.CharField(default='Configured satellite imagery basemap', max_length=160)),
                ('imagery_capture_date', models.DateField(blank=True, null=True)),
                ('imagery_reference', models.URLField(blank=True, help_text='Optional source, catalogue, or scene URL.')),
                ('method', models.CharField(choices=[('visual', 'Human visual review'), ('external', 'External analysis provider')], default='visual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Review'), ('in_review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('provider_job_id', models.CharField(blank=True, max_length=160)),
                ('provider_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='earth_observation.areaofinterest')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observation_surveys', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_observation_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('detection_source', models.CharField(choices=[('human', 'Human mapped'), ('provider', 'External provider suggestion')], default='human', max_length=20)),
                ('provider_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('suspected', 'Suspected Dumpsite'), ('dismissed', 'Dismissed'), ('report_created', 'Report Created')], default='unreviewed', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_candidate', to='reports.report')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_observation_candidates', to=settings.AUTH_USER_MODEL)),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_candidates', to='reports.wastecategory')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='earth_observation.observationsurvey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='areaofinterest',
            constraint=models.UniqueConstraint(fields=('county', 'name'), name='unique_county_observation_area'),
        ),
    ]
