# Generated by Django 6.0.7 on 2026-08-24 20:41

import accounts.models
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.BlueWatchUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, numbers, spaces and @/./+/-/_ only.', max_length=150, unique=True, validators=[accounts.validators.BlueWatchUsernameValidator()], verbose_name='username'),
        ),
    ]
