# Generated by Django 6.0.7 on 2026-07-20 11:17

import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('risk_weight', models.PositiveSmallIntegerField(default=5)),
                ('hazardous', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('source', models.CharField(choices=[('public', 'Public'), ('officer', 'Officer')], default='public', max_length=10)),
                ('reporter_name', models.CharField(blank=True, max_length=120)),
                ('reporter_phone', models.CharField(blank=True, max_length=30)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('location_description', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('original_image', models.ImageField(upload_to=reports.models.safe_report_path, validators=[reports.models.validate_image])),
                ('estimated_size', models.CharField(choices=[('small', 'Small (a few bags)'), ('medium', 'Medium (pickup load)'), ('large', 'Large (truck load)'), ('extensive', 'Extensive')], max_length=20)),
                ('proximity_to_water', models.CharField(choices=[('in_water', 'In water'), ('under_50', 'Under 50 metres'), ('under_200', '50–200 metres'), ('over_200', 'Over 200 metres'), ('unknown', 'Unknown')], max_length=20)),
                ('description', models.TextField()),
                ('date_observed', models.DateField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('needs_info', 'Needs More Information')], default='pending', max_length=20)),
                ('operational_status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('assigned', 'Assigned'), ('cleanup_in_progress', 'Cleanup in Progress'), ('cleaned', 'Cleaned'), ('closed', 'Closed')], default='reported', max_length=30)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=12)),
                ('near_authorized_site', models.BooleanField(default=False)),
                ('authorized_site_note', models.CharField(blank=True, max_length=255)),
                ('analysis_status', models.CharField(choices=[('not_analysed', 'Not Analysed'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('human_review', 'Requires Human Review')], default='not_analysed', max_length=20)),
                ('analysis_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('analysis_notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='locations.county')),
                ('possible_duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possible_duplicates', to='reports.report')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='locations.ward')),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_suggestions', to='reports.wastecategory')),
                ('waste_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reports.wastecategory')),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='MarineImpactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_removed_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recycled_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('high_risk_near_water_resolved', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='impact_record', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('previous_value', models.CharField(blank=True, max_length=100)),
                ('new_value', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='reports.report')),
                ('responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
