# Generated by Django 6.0.8 on 2026-10-01 12:56

from django.db import migrations, models


def create_unclassified_category(apps, schema_editor):
    WasteCategory = apps.get_model('reports', 'WasteCategory')
    WasteCategory.objects.update_or_create(
        slug='unclassified',
        defaults={'name': 'Unclassified photo report', 'risk_weight': 5, 'hazardous': False, 'is_active': True},
    )


def remove_unclassified_category(apps, schema_editor):
    apps.get_model('reports', 'WasteCategory').objects.filter(slug='unclassified').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='estimated_size',
            field=models.CharField(choices=[('unknown', 'Not estimated'), ('small', 'Small (a few bags)'), ('medium', 'Medium (pickup load)'), ('large', 'Large (truck load)'), ('extensive', 'Extensive')], max_length=20),
        ),
        migrations.RunPython(create_unclassified_category, remove_unclassified_category),
    ]
