# Generated by Django 6.0.7 on 2026-07-20 11:17

import django.db.models.deletion
import operations.models
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleanup_teams', to='locations.county')),
                ('members', models.ManyToManyField(blank=True, related_name='cleanup_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CleanupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('high', 'High'), ('urgent', 'Urgent')], default='routine', max_length=12)),
                ('scheduled_cleanup_date', models.DateField()),
                ('instructions', models.TextField()),
                ('assignment_status', models.CharField(choices=[('new', 'New'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Verification'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_waste_collected_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disposal_destination', models.CharField(blank=True, max_length=200)),
                ('waste_diverted_for_recycling_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('before_photo', models.ImageField(blank=True, upload_to=operations.models.evidence_path, validators=[reports.models.validate_image])),
                ('after_photo', models.ImageField(blank=True, upload_to=operations.models.evidence_path, validators=[reports.models.validate_image])),
                ('completion_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='reports.report')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='operations.cleanupteam')),
            ],
            options={
                'ordering': ['scheduled_cleanup_date'],
            },
        ),
    ]
